nu = int(input('Digite o numero que deseja a tabuada '))
t1 = nu * 1
t2 = nu * 2
t3 = nu * 3
t4 = nu * 4
t5 = nu * 5
t6 = nu * 6
t7 = nu * 7
t8 = nu * 8
t9 = nu * 9
t10 = nu * 10
print('A tabuada de {} é: \n'
      '{} X 1 = {}\n'
      '{} x 2 = {}\n'
      '{} X 3 = {}\n'
      '{} X 4 = {}\n'
      '{} X 5 = {}\n'
      '{} X 6 = {}\n'
      '{} X 7 = {}\n'
      '{} X 8 = {}\n'
      '{} X 9 = {}\n'
      '{} X 10 = {}\n'.format(nu, nu, t1, nu, t2, nu, t3, nu, t4, nu, t5, nu, t6, nu, t7, nu, t8, nu, t9, nu, t10))
